name: Blazorise Push CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        include-prerelease: true

    - name: Restore NuGet Packages
      run: dotnet restore
      
    - name: test compiler proj
      run: dotnet build --configuration Release --no-restore Documentation/Blazorise.Docs.Compiler
      
